// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ccv-ux/Executive.tsx": () => import("../components/mockups/ccv-ux/Executive.tsx"),
  "./components/mockups/ccv-ux/Operations.tsx": () => import("../components/mockups/ccv-ux/Operations.tsx")
};
