import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { toast } from "sonner";
import { useAuth } from "@/hooks/use-auth";
import { createAjusteHttp, createUsuarioHttp, deleteAjusteHttp, deleteUsuarioHttp, getAjustesHttp, getUsuariosHttp, updateUsuarioHttp } from "@/lib/administracion-http";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

function Denied({ admin = false }: { admin?: boolean }) { return <div className="card-elevated max-w-xl p-8 text-center"><h2 className="font-display text-xl font-semibold">Acceso restringido</h2><p className="mt-2 text-sm text-muted-foreground">{admin ? "Esta superficie requiere Gerencia y administrador de la aplicación." : "Esta superficie requiere el rol Gerencia."}</p></div>; }
export function UsuariosPage() {
  const { role } = useAuth(); const qc = useQueryClient(); const [form, setForm] = useState({ email: "", password: "", nombreCompleto: "", role: "asesor" });
  const data = useQuery({ queryKey: ["usuarios"], queryFn: getUsuariosHttp }); const create = useMutation({ mutationFn: () => createUsuarioHttp({ ...form, sucursalId: null, unidadNegocioId: null }), onSuccess: () => { toast.success("Usuario creado"); setForm({ email: "", password: "", nombreCompleto: "", role: "asesor" }); qc.invalidateQueries({ queryKey: ["usuarios"] }); }, onError: (e: Error) => toast.error(e.message) });
  const remove = useMutation({ mutationFn: deleteUsuarioHttp, onSuccess: () => qc.invalidateQueries({ queryKey: ["usuarios"] }), onError: (e: Error) => toast.error(e.message) });
  const changeRole = useMutation({ mutationFn: ({ id, role }: { id: string; role: string }) => updateUsuarioHttp(id, { role }), onSuccess: () => qc.invalidateQueries({ queryKey: ["usuarios"] }), onError: (e: Error) => toast.error(e.message) });
  if (role !== "gerencia") return <Denied />;
  const roleFor = (userId: string) => data.data?.roles.find((r) => r.userId === userId)?.role ?? "asesor";
  return <div className="space-y-6"><header><p className="text-xs font-semibold uppercase text-primary">Administración</p><h2 className="font-display text-3xl font-semibold">Usuarios y permisos</h2></header>
    <section className="card-elevated grid gap-3 p-5 md:grid-cols-5"><Input placeholder="Nombre completo" value={form.nombreCompleto} onChange={e => setForm({ ...form, nombreCompleto: e.target.value })} /><Input placeholder="correo@empresa.com" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /><Input type="password" placeholder="Contraseña (8+)" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /><select className="rounded-md border bg-background px-3" value={form.role} onChange={e => setForm({ ...form, role: e.target.value })}>{["gerencia","gerente_comercial","coordinador","asesor"].map(x => <option key={x}>{x}</option>)}</select><Button disabled={create.isPending} onClick={() => create.mutate()}>Crear usuario</Button></section>
    <section className="card-elevated overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Nombre</th><th>Correo</th><th>Rol</th><th>Estado</th><th /></tr></thead><tbody>{data.data?.users.map(u => { const p = data.data?.profiles.find(x => x.id === u.id); return <tr className="border-b" key={u.id}><td className="p-3">{p?.nombreCompleto ?? "—"}</td><td>{u.email}</td><td><select className="rounded border bg-background p-1" value={roleFor(u.id)} onChange={e => changeRole.mutate({ id: u.id, role: e.target.value })}>{["gerencia","gerente_comercial","coordinador","asesor"].map(x => <option key={x}>{x}</option>)}</select></td><td>{u.isActive ? "Activo" : "Inactivo"}</td><td><Button size="sm" variant="ghost" onClick={() => remove.mutate(u.id)}>Eliminar</Button></td></tr>; })}</tbody></table></section></div>;
}
export function AjustesPage() {
  const { role, profile } = useAuth(); const qc = useQueryClient(); const year = new Date().getFullYear(); const [form, setForm] = useState({ mes: String(new Date().getMonth() + 1), monto: "", motivo: "" });
  const data = useQuery({ queryKey: ["ajustes", year], queryFn: () => getAjustesHttp(year), enabled: role === "gerencia" && !!profile?.is_admin }); const create = useMutation({ mutationFn: () => createAjusteHttp({ anio: year, mes: Number(form.mes), monto: Number(form.monto), motivo: form.motivo, sucursalId: null, unidadNegocioId: null }), onSuccess: () => { setForm({ mes: form.mes, monto: "", motivo: "" }); qc.invalidateQueries({ queryKey: ["ajustes"] }); }, onError: (e: Error) => toast.error(e.message) }); const del = useMutation({ mutationFn: deleteAjusteHttp, onSuccess: () => qc.invalidateQueries({ queryKey: ["ajustes"] }) });
  if (role !== "gerencia" || !profile?.is_admin) return <Denied admin />;
  return <div className="space-y-6"><header><p className="text-xs font-semibold uppercase text-primary">Administración</p><h2 className="font-display text-3xl font-semibold">Ajustes manuales</h2></header><section className="card-elevated grid gap-3 p-5 md:grid-cols-4"><Input type="number" min="1" max="12" value={form.mes} onChange={e => setForm({ ...form, mes: e.target.value })} /><Input type="number" placeholder="Monto" value={form.monto} onChange={e => setForm({ ...form, monto: e.target.value })} /><Input placeholder="Motivo obligatorio" value={form.motivo} onChange={e => setForm({ ...form, motivo: e.target.value })} /><Button onClick={() => create.mutate()}>Registrar ajuste</Button></section><section className="card-elevated overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Mes</th><th>Monto</th><th>Motivo</th><th>Alcance</th><th /></tr></thead><tbody>{data.data?.map(a => <tr className="border-b" key={a.id}><td className="p-3">{a.mes}/{a.anio}</td><td>{Number(a.monto).toLocaleString()}</td><td>{a.motivo}</td><td>{a.sucursal} / {a.unidad}</td><td><Button size="sm" variant="ghost" onClick={() => del.mutate(a.id)}>Eliminar</Button></td></tr>)}</tbody></table></section></div>;
}
export function CargaPage() { const { role } = useAuth(); if (role !== "gerencia") return <Denied />; return <div className="card-elevated max-w-3xl p-8"><h2 className="font-display text-3xl font-semibold">Carga de datos</h2><p className="mt-3 text-sm text-muted-foreground">La carga de Excel requiere el servicio de importación habilitado en el servidor.</p><Label className="mt-6 block">Archivo Excel</Label><Input className="mt-2" type="file" accept=".xlsx,.xls" disabled /><p className="mt-2 text-xs text-muted-foreground">La interfaz se mantiene restringida a Gerencia.</p></div>; }